version: "3"

services:
  db:
    image: postgres:16.4-alpine
    container_name: quibble_db
    restart: always
    environment:
      POSTGRES_DB: quibble_db
      POSTGRES_PASSWORD: quibble_pass
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
